site_name: Testing mkdocs
site_url: https://binnes.github.io/mkdocTest
repo_url: https://github.com/binnes/mkdocTest
theme:
    name: mkdocs
#    name: readthedocs
    nav_style: dark
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
markdown_extensions:
  - attr_list
nav:
  - Home: index.md
  - Actions: GitHubActions.md
  - MkDocs: MkDocs.md
  - Pages: GitHubPages.md
google_analytics: ['UA-172132667-1', 'binnes.github.io/mkdocTest']
